"""Structural types (PEP 544 Protocols) for the compiled ``flukenorma._core`` objects.

The pybind11 extension ships no type stubs, so every attribute on it is ``Any``
to a static type checker.  The Protocols below describe the exact shapes of the
objects the extension returns and accepts (see ``module/bindings/python/src/
module.cpp``), which gives the wrapper — and code written against it — full
static typing without needing the compiled module at type-check time.

``NormaLike`` doubles as a seam for testing: any object that satisfies it
(e.g. a hand-written fake) can be handed to :class:`flukenorma.Norma` in place
of a live instrument.
"""

from __future__ import annotations

from typing import Protocol, Sequence, runtime_checkable


@runtime_checkable
class CoreEnumLike(Protocol):
    """A pybind11 enum value (``flukenorma._core.WiringSystem`` etc.).

    Python :class:`enum.Enum` members satisfy this too, which lets fakes
    return the wrapper's own enums directly.
    """

    @property
    def name(self) -> str: ...

    @property
    def value(self) -> int: ...


@runtime_checkable
class IdentificationLike(Protocol):
    """Parsed ``*IDN?`` response as returned by ``flukenorma._core.Identification``."""

    @property
    def manufacturer(self) -> str: ...

    @property
    def model(self) -> str: ...

    @property
    def serial_number(self) -> str: ...

    @property
    def firmware_version(self) -> str: ...


@runtime_checkable
class ScpiErrorInfoLike(Protocol):
    """One entry from the instrument error queue (``SYSTem:ERRor?``)."""

    @property
    def code(self) -> int: ...

    @property
    def message(self) -> str: ...


@runtime_checkable
class ReadingLike(Protocol):
    """Result of ``DATA:STATus?``: one status flag per measurement value."""

    @property
    def values(self) -> list[float]: ...

    @property
    def status(self) -> list[int]: ...


@runtime_checkable
class DataFormatSettingLike(Protocol):
    """Result of ``FORMat[:DATA]?``: the transfer format and its length."""

    @property
    def format(self) -> CoreEnumLike: ...

    @property
    def length(self) -> int: ...


@runtime_checkable
class DateLike(Protocol):
    """A calendar date as ``SYSTem:DATE`` reports it."""

    @property
    def year(self) -> int: ...

    @property
    def month(self) -> int: ...

    @property
    def day(self) -> int: ...


@runtime_checkable
class TimeLike(Protocol):
    """A time of day as ``SYSTem:TIME`` reports it."""

    @property
    def hours(self) -> int: ...

    @property
    def minutes(self) -> int: ...

    @property
    def seconds(self) -> int: ...


@runtime_checkable
class DataPreambleLike(Protocol):
    """Result of ``CALCulate:DATA:PREamble?`` / ``TRACe:DATA:PREamble?``."""

    @property
    def count(self) -> int: ...

    @property
    def function_count(self) -> int: ...

    @property
    def interval(self) -> float: ...

    @property
    def start(self) -> float: ...

    @property
    def functions(self) -> list[str]: ...

    @property
    def raw(self) -> str: ...


@runtime_checkable
class NormaLike(Protocol):
    """The interface of ``flukenorma._core.Norma`` (the compiled instrument class).

    Timeouts, the aperture and every other duration are in seconds; ``phase``
    follows the manual's phase suffixes (1..6 = L1..L6, 12/23/31/... =
    phase-to-phase, 0 = totals), and ``channel`` is a hardware input channel
    1..12 (the current inputs are the odd ones).

    Enum-valued parameters and results are ``CoreEnumLike``: the wrapper bridges
    them to and from its own :mod:`enum` members by name, so a fake may return
    either kind.
    """

    # -- Lifecycle -----------------------------------------------------------
    def close(self) -> None: ...

    @property
    def is_open(self) -> bool: ...

    def prepare(self) -> None: ...

    # -- Raw SCPI escape hatches ----------------------------------------------
    def write(self, scpi: str) -> None: ...

    def query(self, scpi: str) -> str: ...

    # -- IEEE 488.2 common commands ---------------------------------------------
    def identify(self) -> IdentificationLike: ...

    def reset(self) -> None: ...

    def clear_status(self) -> None: ...

    def options(self) -> str: ...

    def learn(self) -> str: ...

    def wait_operation_complete(self, timeout: float = ...) -> None: ...

    def set_operation_complete_flag(self) -> None: ...

    def wait_pending_operations(self) -> None: ...

    def trigger(self) -> None: ...

    def set_event_status_enable(self, mask: int) -> None: ...

    def event_status_enable(self) -> int: ...

    def event_status(self) -> int: ...

    def set_service_request_enable(self, mask: int) -> None: ...

    def service_request_enable(self) -> int: ...

    def status_byte(self) -> int: ...

    def save_setup(self, slot: int) -> None: ...

    def recall_setup(self, slot: int) -> None: ...

    # -- ROUTe --------------------------------------------------------------------
    def set_wiring_system(self, system: CoreEnumLike) -> None: ...

    def wiring_system(self) -> CoreEnumLike: ...

    # -- INPut ---------------------------------------------------------------------
    def set_input_coupling(self, channel: int, coupling: CoreEnumLike) -> None: ...

    def input_coupling(self, channel: int) -> CoreEnumLike: ...

    def set_input_gain(self, channel: int, gain: float) -> None: ...

    def input_gain(self, channel: int) -> float: ...

    def set_input_filter(self, channel: int, on: bool = ...) -> None: ...

    def input_filter(self, channel: int) -> bool: ...

    def input_filter_frequency(self, channel: int) -> float: ...

    def set_input_shunt(self, channel: int, shunt: CoreEnumLike) -> None: ...

    def input_shunt(self, channel: int) -> CoreEnumLike: ...

    # -- SENSe: ranging, scaling, averaging -----------------------------------------
    def set_voltage_range(self, phase: int, volts: float) -> None: ...

    def voltage_range(self, phase: int) -> float: ...

    def set_voltage_autorange(self, phase: int, on: bool = ...) -> None: ...

    def voltage_autorange(self, phase: int) -> bool: ...

    def voltage_ranges(self, phase: int) -> list[float]: ...

    def set_voltage_scale(self, phase: int, ratio: float) -> None: ...

    def voltage_scale(self, phase: int) -> float: ...

    def set_current_range(self, phase: int, amps: float) -> None: ...

    def current_range(self, phase: int) -> float: ...

    def set_current_autorange(self, phase: int, on: bool = ...) -> None: ...

    def current_autorange(self, phase: int) -> bool: ...

    def current_ranges(self, phase: int) -> list[float]: ...

    def set_current_scale(self, phase: int, ratio: float) -> None: ...

    def current_scale(self, phase: int) -> float: ...

    def set_aperture(self, seconds: float) -> None: ...

    def aperture(self) -> float: ...

    def sampling_frequency(self) -> float: ...

    # -- SYNC -------------------------------------------------------------------------
    def set_sync_enabled(self, on: bool = ...) -> None: ...

    def sync_enabled(self) -> bool: ...

    def set_sync_source(self, source: str) -> None: ...

    def sync_source(self) -> str: ...

    def sync_to_voltage(self, phase: int) -> None: ...

    def sync_to_current(self, phase: int) -> None: ...

    def sync_external(self) -> None: ...

    def set_sync_level(self, level: float) -> None: ...

    def sync_level(self) -> float: ...

    def set_sync_level_unit(self, unit: CoreEnumLike) -> None: ...

    def sync_level_unit(self) -> CoreEnumLike: ...

    def set_sync_slope(self, slope: CoreEnumLike) -> None: ...

    def sync_slope(self) -> CoreEnumLike: ...

    def set_sync_filter(self, on: bool = ...) -> None: ...

    def sync_filter(self) -> bool: ...

    def set_sync_filter_frequency(self, hertz: float) -> None: ...

    def sync_filter_frequency(self) -> float: ...

    def set_sync_timeout(self, seconds: float) -> None: ...

    def sync_timeout(self) -> float: ...

    # -- SENSe: measurement functions ---------------------------------------------------
    def set_functions(self, functions: Sequence[str]) -> None: ...

    def functions(self) -> list[str]: ...

    def enable_all_functions(self) -> None: ...

    def clear_functions(self) -> None: ...

    def function_count(self) -> int: ...

    def set_concurrent(self, on: bool = ...) -> None: ...

    def concurrent(self) -> bool: ...

    # -- Acquisition ---------------------------------------------------------------------
    def set_continuous(self, on: bool = ...) -> None: ...

    def continuous(self) -> bool: ...

    def initiate(self) -> None: ...

    def initiate_sweep(self, block: CoreEnumLike) -> None: ...

    def abort(self) -> None: ...

    # -- TRIGger --------------------------------------------------------------------------
    def set_trigger_start_source(self, source: str) -> None: ...

    def trigger_start_source(self) -> str: ...

    def set_trigger_start_level(self, level: float) -> None: ...

    def trigger_start_level(self) -> float: ...

    def set_trigger_start_slope(self, slope: CoreEnumLike) -> None: ...

    def trigger_start_slope(self) -> CoreEnumLike: ...

    def set_trigger_start_time(self, date: DateLike, time: TimeLike) -> None: ...

    def set_trigger_stop_source(self, source: str) -> None: ...

    def trigger_stop_source(self) -> str: ...

    def set_trigger_stop_level(self, level: float) -> None: ...

    def trigger_stop_level(self) -> float: ...

    def set_trigger_stop_slope(self, slope: CoreEnumLike) -> None: ...

    def trigger_stop_slope(self) -> CoreEnumLike: ...

    def set_trigger_stop_time(self, date: DateLike, time: TimeLike) -> None: ...

    # -- Data -------------------------------------------------------------------------------
    def data(self, functions: Sequence[str] = ...) -> list[float]: ...

    def data_with_status(self, functions: Sequence[str] = ...) -> ReadingLike: ...

    # -- CALCulate: spectrum and harmonics ---------------------------------------------------
    def set_harmonic_order(self, order: int) -> None: ...

    def harmonic_order(self) -> int: ...

    def transform_once(self) -> None: ...

    def set_transform_mode(self, mode: CoreEnumLike) -> None: ...

    def transform_mode(self) -> CoreEnumLike: ...

    def set_transform_functions(self, functions: Sequence[str]) -> None: ...

    def transform_functions(self) -> list[str]: ...

    def set_transform_start(self, hertz: float) -> None: ...

    def transform_start(self) -> float: ...

    def set_transform_stop(self, hertz: float) -> None: ...

    def transform_stop(self) -> float: ...

    def set_transform_cycles(self, cycles: int) -> None: ...

    def transform_cycles(self) -> int: ...

    def set_transform_grouping(self, grouping: CoreEnumLike) -> None: ...

    def transform_grouping(self) -> CoreEnumLike: ...

    def transform_data(self, count: int = ..., offset: int = ...) -> list[float]: ...

    def transform_preamble(self) -> DataPreambleLike: ...

    def transform_thd(self) -> list[float]: ...

    # -- CALCulate: integration ------------------------------------------------------------
    def set_integral_enabled(self, on: bool = ...) -> None: ...

    def integral_enabled(self) -> bool: ...

    def set_integral_functions(self, functions: Sequence[str]) -> None: ...

    def integral_functions(self) -> list[str]: ...

    def clear_integral(self) -> None: ...

    def set_integral_auto_clear(self, on: bool = ...) -> None: ...

    def integral_auto_clear(self) -> bool: ...

    def set_integral_start_source(self, source: CoreEnumLike) -> None: ...

    def integral_start_source(self) -> CoreEnumLike: ...

    def start_integral(self) -> None: ...

    def set_integral_start_time(self, date: DateLike, time: TimeLike) -> None: ...

    def set_integral_stop_source(self, source: CoreEnumLike) -> None: ...

    def integral_stop_source(self) -> CoreEnumLike: ...

    def stop_integral(self) -> None: ...

    def set_integral_stop_time(self, date: DateLike, time: TimeLike) -> None: ...

    def set_integral_stop_interval(self, seconds: float) -> None: ...

    def integral_stop_interval(self) -> float: ...

    # -- CALCulate: power --------------------------------------------------------------------
    def set_power_correction(self, correction: CoreEnumLike) -> None: ...

    def power_correction(self) -> CoreEnumLike: ...

    def set_efficiency_reference(self, input: str, output: str, phase: int = ...) -> None: ...

    # -- Memory recording ----------------------------------------------------------------------
    def set_sweep_enabled(self, block: CoreEnumLike, on: bool = ...) -> None: ...

    def sweep_enabled(self, block: CoreEnumLike) -> bool: ...

    def set_sweep_time(self, block: CoreEnumLike, seconds: float) -> None: ...

    def set_sweep_time_max(self, block: CoreEnumLike) -> None: ...

    def sweep_time(self, block: CoreEnumLike) -> float: ...

    def set_sweep_offset_time(self, block: CoreEnumLike, seconds: float) -> None: ...

    def sweep_offset_time(self, block: CoreEnumLike) -> float: ...

    def sweep_points(self, block: CoreEnumLike) -> int: ...

    def sweep_offset_points(self, block: CoreEnumLike) -> int: ...

    def set_sweep_count(self, block: CoreEnumLike, count: int) -> None: ...

    def sweep_count(self, block: CoreEnumLike) -> int: ...

    def set_sweep_sparsing(self, block: CoreEnumLike, factor: int) -> None: ...

    def sweep_sparsing(self, block: CoreEnumLike) -> int: ...

    def set_sweep_functions(self, block: CoreEnumLike, functions: Sequence[str]) -> None: ...

    def sweep_functions(self, block: CoreEnumLike) -> list[str]: ...

    def trace_preamble(self, block: CoreEnumLike) -> DataPreambleLike: ...

    def trace_data(
        self, block: CoreEnumLike, count: int = ..., offset: int = ..., sparsing: int = ...
    ) -> list[float]: ...

    def trace_status(
        self, block: CoreEnumLike, count: int = ..., offset: int = ..., sparsing: int = ...
    ) -> list[int]: ...

    def trace_free(self) -> int: ...

    def trace_length(self) -> int: ...

    def delete_traces(self) -> None: ...

    # -- FORMat -----------------------------------------------------------------------------------
    def set_data_format(self, format: CoreEnumLike, length: int = ...) -> None: ...

    def data_format(self) -> DataFormatSettingLike: ...

    def set_status_format(self, format: CoreEnumLike, length: int = ...) -> None: ...

    def status_format(self) -> DataFormatSettingLike: ...

    def set_byte_order(self, order: CoreEnumLike) -> None: ...

    def byte_order(self) -> CoreEnumLike: ...

    def set_transpose(self, on: bool = ...) -> None: ...

    def transpose(self) -> bool: ...

    # -- DISPlay and OUTPut -------------------------------------------------------------------------
    def set_display_enabled(self, on: bool = ...) -> None: ...

    def display_enabled(self) -> bool: ...

    def set_display_functions(self, functions: Sequence[str]) -> None: ...

    def display_functions(self) -> list[str]: ...

    def set_output_enabled(self, on: bool = ...) -> None: ...

    def output_enabled(self) -> bool: ...

    # -- SYSTem ---------------------------------------------------------------------------------------
    def scpi_version(self) -> str: ...

    def set_key_lock(self, lock: CoreEnumLike) -> None: ...

    def key_lock(self) -> CoreEnumLike: ...

    def set_date(self, date: DateLike) -> None: ...

    def date(self) -> DateLike: ...

    def set_time(self, time: TimeLike) -> None: ...

    def time_of_day(self) -> TimeLike: ...

    def set_gpib_address(self, address: int) -> None: ...

    def gpib_address(self) -> int: ...

    def set_serial_baud(self, baud: int) -> None: ...

    def serial_baud(self) -> int: ...

    def set_language(self, language: str) -> None: ...

    def language(self) -> str: ...

    # -- TIMer ----------------------------------------------------------------------------------------
    def reset_timer(self) -> None: ...

    def timer_reset_time(self) -> float: ...

    # -- STATus ----------------------------------------------------------------------------------------
    def status(self, register: CoreEnumLike, part: CoreEnumLike) -> int: ...

    def set_status(self, register: CoreEnumLike, part: CoreEnumLike, mask: int) -> None: ...

    def status_operation_condition(self) -> int: ...

    # -- Errors & status --------------------------------------------------------------------------------
    def read_errors(self) -> list[ScpiErrorInfoLike]: ...

    def read_errors_at_once(self) -> list[ScpiErrorInfoLike]: ...

    def check_errors(self) -> None: ...

    # -- Plumbing --------------------------------------------------------------------------------------
    def set_timeout(self, timeout: float) -> None: ...

    @property
    def timeout(self) -> float: ...
